### ISSUE TITLE
Kafka  version upgrade

### ISSUE THREAD

**Issue by EvanSole** [ptgoetz/logback-kafka#2]
Kafka  0.7.1  upgrade Kafka  0.8.1.1

1) pom.xml

  <dependency>
         <groupId>org.apache.kafka</groupId>
         <artifactId>kafka_2.9.2</artifactId>
         <version>0.8.1.1</version>
 </dependency>
 <dependency>
         <groupId>org.scala-lang</groupId>
        <artifactId>scala-library</artifactId>
        <version>2.9.2</version>
</dependency>

2)logback-formatter.xml & logback.xml

The new attribute  "broker"
<appender name="KAFKA" class="com.github.ptgoetz.logback.kafka.KafkaAppender">
    <topic>logback_topic</topic>
    <zookeeperHost>localhost:2181</zookeeperHost>
    <broker>localhost:9092</broker>
</appender>

3) Use of kafka version of the API to producer
    .....
    @Override
    public void start() {
        if (this.formatter == null) {
            this.formatter = new MessageFormatter();
        }
        super.start();
        Properties props = new Properties();
        props.put("zk.connect", this.zookeeperHost);
        props.put("metadata.broker.list", this.broker);
        props.put("serializer.class", "kafka.serializer.StringEncoder");
        props.put("zk.connectiontimeout.ms","15000");
        props.put("request.required.acks","1");
        ProducerConfig config = new ProducerConfig(props);
        this.producer = new Producer<String, String>(config);
    }

```
@Override
public void stop() {
    super.stop();
    this.producer.close();
}

@Override
protected void append(ILoggingEvent event) {
  try{
      String payload = this.formatter.format(event);
      KeyedMessage<String, String> message = new KeyedMessage<String, String>(topic, payload);
    this.producer.send(message);
    }catch(Exception e){
         e.printStackTrace();
   }
```

   }

Also please advice .

thank you !

**Comment by ralph-tice** [comment]
I think https://github.com/abdulkadiryaman/logback-kafka is the most up to date branch in the network of logback-kafka.  I just verified that fork is working on kafka 0.8 using the artifact from clojars, anyway.
